# See https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example

[advisories]
ignore = [
    "RUSTSEC-2023-0071", # we're using postgres, this is likely a false positive: https://github.com/launchbadge/sqlx/issues/2911
    "RUSTSEC-2024-0373", # we're not using http3 in reqwest, we end up getting quinn due to a bug in cargo, it's not being compiled: https://github.com/seanmonstar/reqwest/issues/2318 / https://github.com/rust-lang/cargo/issues/10802
]
