name: Pyiceberg Integration

on:
  push:
    branches:
      - main
  pull_request:


env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker info
        run: docker info

      - name: Build Docker image (amd64)
        run: |
          DOCKER_BUILDKIT=1 docker build -t localhost/iceberg-catalog-local:amd64 \
          -f docker/full.Dockerfile .
          docker save -o /tmp/iceberg-catalog-amd64.tar localhost/iceberg-catalog-local:amd64

      - name: Save Docker
        uses: actions/upload-artifact@v4
        with:
          name: iceberg-catalog-image
          path: /tmp/*.tar

  test-pyiceberg:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore binary
        uses: actions/download-artifact@v4
        with:
          name: iceberg-catalog-image
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -Rlh artifacts

      - name: Restore Docker image
        run: |
          docker load -i artifacts/iceberg-catalog-amd64.tar

      - name: Test Pyiceberg
        run: |
          cd tests &&
          docker compose run --quiet-pull spark /opt/entrypoint.sh bash -c "cd /opt/tests && bash run_pyiceberg.sh"

        env:
          LAKEKEEPER_TEST__SPARK_IMAGE: apache/spark:3.5.1-java17-python3
          LAKEKEEPER_TEST__SERVER_IMAGE: localhost/iceberg-catalog-local:amd64
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2