name: 🚀 Release

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '.github/workflows/release.yml'
  workflow_dispatch:

env:
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  # Publish the build output as CI artifact to inspect
  preview: ${{ !startsWith(github.ref, 'refs/tags/') || github.repository != 'hansetag/iceberg-catalog' }}

jobs:
  # Update release PR
  release_please:
    name: Release Please
    runs-on: ubuntu-latest
    if: github.repository == 'hansetag/iceberg-catalog'
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: rust

  build-binary:
    name: Build Binary
    needs:
      - release_please
    if: ${{ needs.release_please.outputs.release_created == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
    # not supported by windows nor macos
    # services:
    #   postgres:
    #     image: postgres:16
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: postgres
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432
    strategy:
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
          name: iceberg-catalog-x86_64-unknown-linux-gnu.tar.gz
          cross: false

        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
          name: iceberg-catalog-x86_64-unknown-linux-musl.tar.gz
          cross: true

        - target: aarch64-unknown-linux-musl
          os: ubuntu-latest
          name: iceberg-catalog-aarch64-unknown-linux-musl.tar.gz
          cross: true

        # Currently disabled due to https://github.com/actions/runner-images/issues/9460
        # Which prevents us from launching postgres via docker / colima
        # - target: aarch64-apple-darwin
        #   os: macos-14
        #   name: iceberg-catalog-aarch64-apple-darwin.tar.gz
        #   cross: false

        - target: x86_64-pc-windows-msvc
          os: windows-latest
          name: iceberg-catalog-x86_64-pc-windows-msvc.zip
          rustflags: -C target-feature=+crt-static
          cross: false

        - target: aarch64-pc-windows-msvc
          os: windows-latest
          name: iceberg-catalog-aarch64-pc-windows-msvc.zip
          rustflags: -C target-feature=+crt-static
          cross: false

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    env:
      RUSTFLAGS: ${{ matrix.rustflags || '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          cache: false
      
      # - name: Setup docker (missing on MacOS)
      #   if: matrix.os == 'macos-14'
      #   run: |
      #     brew install docker
      #     # Docker on macOS misses daemon due to licensing, so install colima as runtime
      #     brew install colima
      #     colima start

      - name: Run postgres
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker run -d --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres -p 5432:5432 postgres:16
          docker ps -a

      - name: Install cross
        if: matrix.cross == true
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Migrate database [-nix]
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get install libpq-dev -y
          cargo install --version=0.7.4 sqlx-cli --no-default-features --features postgres
          cd crates/iceberg-catalog
          sqlx database create
          sqlx migrate run
          cd -
          cargo sqlx prepare --workspace
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Test [Cargo]
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo test --all-features --release --locked --target ${{ matrix.target }} --workspace
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Build [Cargo]
        if: matrix.cross == false
        run: cargo build --all-features --release --locked --target ${{ matrix.target }}

      - name: Build [Cross]
        if: matrix.cross == true
        run: cross build --all-features --release --locked --target ${{ matrix.target }}

      - name: Prepare artifacts [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.name }} iceberg-catalog.exe
          cd -

      - name: Prepare artifacts [-nix]
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../${{ matrix.name }} iceberg-catalog
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: build-binary
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: List Artifacts
        run: ls -lh

      - name: Restore Binaries
        run: |
          cd iceberg-catalog-x86_64-unknown-linux-gnu.tar.gz
          tar xzvf iceberg-catalog-x86_64-unknown-linux-gnu.tar.gz
          cd -
          cd iceberg-catalog-aarch64-unknown-linux-musl.tar.gz
          tar xzvf iceberg-catalog-aarch64-unknown-linux-musl.tar.gz
          ls -Rlh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker info
        run: docker info

      - name: Build Docker image (amd64)
        run: |
          DOCKER_BUILDKIT=1 docker build -t localhost/iceberg-catalog-local:amd64 \
            -f docker/bin.Dockerfile \
            --build-arg "BIN=iceberg-catalog-x86_64-unknown-linux-gnu.tar.gz/iceberg-catalog" .

      - name: Build Docker image (arm64)
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --platform linux/arm64 -t localhost/iceberg-catalog-local:arm64 \
            -f docker/bin.Dockerfile \
            --build-arg "BIN=iceberg-catalog-aarch64-unknown-linux-musl.tar.gz/iceberg-catalog" .

      - name: Test Docker (amd64)
        run: |
          cd tests
          docker compose run --quiet-pull spark /opt/entrypoint.sh bash -c "cd /opt/tests && bash run_pyiceberg_and_spark.sh"
          docker compose rm --force
        env:
          ICEBERG_REST_TEST_SERVER_IMAGE: localhost/iceberg-catalog-local:amd64
          ICEBERG_REST_TEST_SPARK_IMAGE: apache/spark:3.5.1-java17-python3

      - name: Test Docker image (arm64)
        run: |
          cd tests
          docker compose run --quiet-pull spark /opt/entrypoint.sh bash -c "cd /opt/tests && bash run_pyiceberg_and_spark.sh"
        env:
          ICEBERG_REST_TEST_SERVER_IMAGE: localhost/iceberg-catalog-local:arm64
          ICEBERG_REST_TEST_SPARK_IMAGE: apache/spark:3.5.1-java17-python3

      - name: Combine Architectures
        run: |
          docker manifest create localhost/iceberg-catalog-local:latest \
            --amend localhost/iceberg-catalog-local:amd64 \
            --amend localhost/iceberg-catalog-local:arm64
          docker save localhost/iceberg-catalog-local:latest -o /tmp/iceberg-catalog-docker.tar

      - name: Save Docker
        uses: actions/upload-artifact@v4
        with:
          name: iceberg-catalog-image
          path: /tmp/iceberg-catalog-docker.tar

  list-artifacts:
    name: List Artifacts
    runs-on: ubuntu-latest
    needs:
      - build-binary
      - build-docker
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: List Artifacts
        run: ls -Rlh

  # Create GitHub release with Rust build targets and release notes
  publish-binary:
    name: Publish Binary
    runs-on: ubuntu-latest
    needs:
      - build-binary
      - build-docker
      - release_please
    if: ${{ needs.release_please.outputs.release_created == 'true' }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Publish Release
        run: gh release edit ${{ needs.release_please.outputs.tag_name }} --draft=false --repo=hansetag/iceberg-catalog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build | Add Artifacts to Release
        uses: softprops/action-gh-release@v2
        with:
          files: iceberg-catalog-*/iceberg-catalog-*.tar.gz
          tag_name: ${{ needs.release_please.outputs.tag_name }}

  publish-container:
    name: Publish Container
    runs-on: ubuntu-latest
    needs:
      - build-docker
      - build-binary
      - release_please
    if: ${{ needs.release_please.outputs.release_created == 'true' }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Tag Images
        run: |
          docker load -i /tmp/iceberg-catalog-docker.tar
          docker tag localhost/iceberg-catalog-local:latest quay.io/hansetag/iceberg-catalog:latest
          docker tag localhost/iceberg-catalog-local:latest ghcr.io/hansetag/iceberg-catalog:v${{ needs.release_please.outputs.major }}
          docker tag localhost/iceberg-catalog-local:latest ghcr.io/hansetag/iceberg-catalog:v${{ needs.release_please.outputs.major }}.${{ needs.release_please.outputs.minor }}
          docker tag localhost/iceberg-catalog-local:latest ghcr.io/hansetag/iceberg-catalog:v${{ needs.release_please.outputs.major }}.${{ needs.release_please.outputs.minor }}.${{ needs.release_please.outputs.patch }}

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: iceberg-catalog
          tags: latest v${{ needs.release_please.outputs.major }} v${{ needs.release_please.outputs.major }}.${{ needs.release_please.outputs.minor }} v${{ needs.release_please.outputs.major }}.${{ needs.release_please.outputs.minor }}.${{ needs.release_please.outputs.patch }}
          registry: quay.io/hansetag
          username: hansetag+githubicebergcatalog
          password: ${{ secrets.QUAY_PASSWORD }}
